
# Site settings
title: IATI Workbench
email: rolf@drostan.org
description: >
  The IATI Workbench is a (growing) set of tools to work with IATI data: create
  network and flow diagrams, check data quality, convert it into other formats.
brand: DataWorkbench

defaults:
  -
    values:
      layout: "default"

remote_theme: data4development/dataworkbench-jekyll-theme
