
# Site settings
title: IATI Workbench
email: rolf@drostan.org
description: >
  The IATI Workbench is a (growing) set of tools to work with IATI data: create
  network and flow diagrams, check data quality, convert it into other formats.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
